FROM mcr.microsoft.com/dotnet/sdk:8.0 as builder
WORKDIR /app

COPY ./dotnet-voyage-log .

RUN dotnet restore
RUN dotnet publish -c Release -o build


FROM mcr.microsoft.com/dotnet/sdk:8.0

ARG POSTGRES_CONNECTION_STRING
ARG INIT_ADMIN_USERNAME
ARG INIT_ADMIN_EMAIL
ARG INIT_ADMIN_PASSWORD
ARG SECRET_KEY
ARG JWT_AUDIENCE
ARG JWT_ISSUER

ENV POSTGRES_CONNECTION_STRING=${POSTGRES_CONNECTION_STRING}
ENV INIT_ADMIN_USERNAME=${INIT_ADMIN_USERNAME}
ENV INIT_ADMIN_EMAIL=${INIT_ADMIN_EMAIL}
ENV INIT_ADMIN_PASSWORD=${INIT_ADMIN_PASSWORD}
ENV SECRET_KEY=${SECRET_KEY}
ENV JWT_AUDIENCE=${JWT_AUDIENCE}
ENV JWT_ISSUER=${JWT_ISSUER}
WORKDIR /App
COPY --from=builder /app/build .
EXPOSE 8080
ENTRYPOINT ["dotnet", "dotnet-voyage-log.dll"]