-- NOTE: SQL query was co-written with ChatGPT

INSERT INTO regions (region_name, country_fk)
values
-- Finland
('Ahvenanmaa', (SELECT country_id FROM countries WHERE country_name = 'Finland')),
('Uusimaa', (SELECT country_id FROM countries WHERE country_name = 'Finland')),
('Pirkanmaa', (SELECT country_id FROM countries WHERE country_name = 'Finland')),
('Varsinais-Suomi', (SELECT country_id FROM countries WHERE country_name = 'Finland')),
('Satakunta', (SELECT country_id FROM countries WHERE country_name = 'Finland')),
('Päijät-Häme', (SELECT country_id FROM countries WHERE country_name = 'Finland')),
('Kanta-häme', (SELECT country_id FROM countries WHERE country_name = 'Finland')),('Etelä-Karjala', (SELECT country_id FROM countries WHERE country_name = 'Finland')),
('Kymenlaakso', (SELECT country_id FROM countries WHERE country_name = 'Finland')),
('Keski-suomi', (SELECT country_id FROM countries WHERE country_name = 'Finland')),
('Etelä-Karjala', (SELECT country_id FROM countries WHERE country_name = 'Finland')),
('Pohjois-Karjala', (SELECT country_id FROM countries WHERE country_name = 'Finland')),('Etelä-Karjala', (SELECT country_id FROM countries WHERE country_name = 'Finland')),
('Etelä-Savo', (SELECT country_id FROM countries WHERE country_name = 'Finland')),('Etelä-Karjala', (SELECT country_id FROM countries WHERE country_name = 'Finland')),
('Pohjois-Savo', (SELECT country_id FROM countries WHERE country_name = 'Finland')),('Etelä-Karjala', (SELECT country_id FROM countries WHERE country_name = 'Finland')),
('Etelä-Pohjanmaa', (SELECT country_id FROM countries WHERE country_name = 'Finland')),('Etelä-Karjala', (SELECT country_id FROM countries WHERE country_name = 'Finland')),
('Keski-Pohjanmaa', (SELECT country_id FROM countries WHERE country_name = 'Finland')),('Etelä-Karjala', (SELECT country_id FROM countries WHERE country_name = 'Finland')),
('Pohjanmaa', (SELECT country_id FROM countries WHERE country_name = 'Finland')),
('Pohjois-Pohjanmaa', (SELECT country_id FROM countries WHERE country_name = 'Finland')),('Etelä-Karjala', (SELECT country_id FROM countries WHERE country_name = 'Finland')),
('Kainuu', (SELECT country_id FROM countries WHERE country_name = 'Finland')),('Etelä-Karjala', (SELECT country_id FROM countries WHERE country_name = 'Finland')),
('Lappi', (SELECT country_id FROM countries WHERE country_name = 'Finland')),('Etelä-Karjala', (SELECT country_id FROM countries WHERE country_name = 'Finland')),

-- Sweden
('Blekinge', (SELECT country_id FROM countries WHERE country_name = 'Sweden')),
('Bohuslän', (SELECT country_id FROM countries WHERE country_name = 'Sweden')),
('Dalarna', (SELECT country_id FROM countries WHERE country_name = 'Sweden')),
('Dalsland', (SELECT country_id FROM countries WHERE country_name = 'Sweden')),
('Gotlanti', (SELECT country_id FROM countries WHERE country_name = 'Sweden')),
('Gästrikland', (SELECT country_id FROM countries WHERE country_name = 'Sweden')),
('Halland', (SELECT country_id FROM countries WHERE country_name = 'Sweden')),
('Hälsingland', (SELECT country_id FROM countries WHERE country_name = 'Sweden')),
('Härjedalen', (SELECT country_id FROM countries WHERE country_name = 'Sweden')),
('Jämtland', (SELECT country_id FROM countries WHERE country_name = 'Sweden')),
('Lappland', (SELECT country_id FROM countries WHERE country_name = 'Sweden')),
('Medelpad', (SELECT country_id FROM countries WHERE country_name = 'Sweden')),
('Närke', (SELECT country_id FROM countries WHERE country_name = 'Sweden')),
('Skåne', (SELECT country_id FROM countries WHERE country_name = 'Sweden')),
('Småland', (SELECT country_id FROM countries WHERE country_name = 'Sweden')),
('Södermanland', (SELECT country_id FROM countries WHERE country_name = 'Sweden')),
('Uppland', (SELECT country_id FROM countries WHERE country_name = 'Sweden')),
('Värmland', (SELECT country_id FROM countries WHERE country_name = 'Sweden')),
('Västerbotten', (SELECT country_id FROM countries WHERE country_name = 'Sweden')),
('Västergötland', (SELECT country_id FROM countries WHERE country_name = 'Sweden')),
('Västmanland', (SELECT country_id FROM countries WHERE country_name = 'Sweden')),
('Ångermanland', (SELECT country_id FROM countries WHERE country_name = 'Sweden')),
('Öland', (SELECT country_id FROM countries WHERE country_name = 'Sweden')),
('Östergötland', (SELECT country_id FROM countries WHERE country_name = 'Sweden')),

-- Norway
('Akershus', (SELECT country_id FROM countries WHERE country_name = 'Norway')),
('Aust-Agder', (SELECT country_id FROM countries WHERE country_name = 'Norway')),
('Buskerud', (SELECT country_id FROM countries WHERE country_name = 'Norway')),
('Finnmark', (SELECT country_id FROM countries WHERE country_name = 'Norway')),
('Hedmark', (SELECT country_id FROM countries WHERE country_name = 'Norway')),
('Hordaland', (SELECT country_id FROM countries WHERE country_name = 'Norway')),
('Møre og Romsdal', (SELECT country_id FROM countries WHERE country_name = 'Norway')),
('Nordland', (SELECT country_id FROM countries WHERE country_name = 'Norway')),
('Nord-Trøndelag', (SELECT country_id FROM countries WHERE country_name = 'Norway')),
('Oppland', (SELECT country_id FROM countries WHERE country_name = 'Norway')),
('Oslo', (SELECT country_id FROM countries WHERE country_name = 'Norway')),
('Rogaland', (SELECT country_id FROM countries WHERE country_name = 'Norway')),
('Sogn og Fjordane', (SELECT country_id FROM countries WHERE country_name = 'Norway')),
('Sør-Trøndelag', (SELECT country_id FROM countries WHERE country_name = 'Norway')),
('Telemark', (SELECT country_id FROM countries WHERE country_name = 'Norway')),
('Troms', (SELECT country_id FROM countries WHERE country_name = 'Norway')),
('Vest-Agder', (SELECT country_id FROM countries WHERE country_name = 'Norway')),
('Vestfold', (SELECT country_id FROM countries WHERE country_name = 'Norway')),
('Østfold', (SELECT country_id FROM countries WHERE country_name = 'Norway'));